// ---------------------------------------------------------------------------
// Custom effect executor
//
// Custom effects have logic too complex for primitive kinds. The LLM generates
// a handler function for each custom effect; the generated code registers all
// handlers in a CustomHandlerMap and passes it to the EffectRunner at startup.
// ---------------------------------------------------------------------------

import type { GameSession, EffectContext, EffectExecutor } from '#chaincraft/types.js';

/**
 * A custom effect handler — same signature as a plain EffectExecutor.
 * Generated by the LLM for each custom effect in the game spec.
 */
export type CustomHandler = (session: GameSession, ctx: EffectContext) => Promise<void>;

/**
 * Map from effect ID to its generated handler function.
 * Built by the deterministic compiler (generated/custom-effects.ts) which imports
 * each LLM-generated function and registers it against its spec effect ID.
 */
export type CustomHandlerMap = Record<string, CustomHandler>;

type CustomEffectDef = { id: string; description?: string };

/**
 * Factory that produces an EffectExecutor bound to the provided handler map.
 * Call once at startup; register the result in the compiled module's effects map.
 */
export function createCustomExecutor(handlers: CustomHandlerMap): EffectExecutor {
  return {
    kind: 'effect-executor',
    execute: async function executeCustom(
      session: GameSession,
      ctx: EffectContext,
    ): Promise<void> {
      const { id } = ctx.effectDef as CustomEffectDef;
      const handler = handlers[id];
      if (!handler) {
        throw new Error(`No custom handler registered for effect "${id}"`);
      }
      await handler(session, ctx);
    },
  };
}
